# 如果版本出现问题，将版本调低到'3'即可
version: '3.8'
services:
  mongodb:
    image: hanhan9449/biubiubiu-mongodb
    build: mongodb
    networks:
      - biubiubiu
  hapi:
    image: hanhan9449/biubiubiu
    build: .
    networks:
      - biubiubiu
    depends_on:
      - mongodb
    ports:
      - 3000:3000
networks:
  biubiubiu:
